version: "3.9"

services:
  exam-app:
    build: .
    container_name: exam_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://abhishekakmadquick:SiaP6iFYzm2YgjDl@exam.0jhqtth.mongodb.net/exam?retryWrites=true&w=majority&appName=exam
      - NODE_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: exam_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
